// Default automotive specifications for Hyundai Alcazar Corporate Diesel seed restoration
export const FALLBACK_ALCAZAR_SPECS: Record<string, any> = {
  "Engine Type": "1.5L U2 CRDi Diesel",
  "Displacement": { "value": 1493, "unit": "cc" },
  "Max Power": { "value": 114, "unit": "bhp@4000rpm" },
  "Max Torque": { "value": 250, "unit": "Nm@1500-2750rpm" },
  "No. of Cylinders": "4",
  "Valves Per Cylinder": "4",
  "Fuel Supply System": "DHOC",
  "Turbo Charger": "Yes",
  "Transmission Type": "Manual",
  "Gearbox": "6-Speed",
  "Drive Type": "FWD",
  "Fuel Type": "Diesel",
  "Diesel Mileage ARAI": { "value": 20.4, "unit": "kmpl" },
  "Diesel Fuel Tank Capacity": { "value": 50, "unit": "Litres" },
  "Emission Norm Compliance": "BS VI 2.0",
  "Front Suspension": "MacPherson suspension",
  "Rear Suspension": "Rear twist beam",
  "Steering Type": "Electric",
  "Steering Column": "Tilt & Telescopic",
  "Front Brake Type": "Disc",
  "Rear Brake Type": "Disc",
  "Alloy Wheel Size Front": { "value": 17, "unit": "Inch" },
  "Alloy Wheel Size Rear": { "value": 17, "unit": "Inch" },
  "Length": { "value": 4560, "unit": "mm" },
  "Width": { "value": 1800, "unit": "mm" },
  "Height": { "value": 1710, "unit": "mm" },
  "Seating Capacity": "7",
  "Wheel Base": { "value": 2760, "unit": "mm" },
  "No. of Doors": "5",
  "Reported Boot Space": { "value": 180, "unit": "Litres" },
  "Power Steering": "Yes",
  "Air Conditioner": "Yes",
  "Heater": "Yes",
  "Adjustable Steering": "Height & Reach",
  "Height Adjustable Driver Seat": "Yes",
  "Ventilated Seats": "Not Available",
  "Electric Adjustable Seats": "Not Available",
  "Automatic Climate Control": "Yes",
  "Accessory Power Outlet": "Yes",
  "Trunk Light": "Yes",
  "Vanity Mirror": "Yes",
  "Rear Reading Lamp": "Yes",
  "Rear Seat Headrest": "Adjustable",
  "Adjustable Headrest": "Yes",
  "Rear Seat Centre Arm Rest": "Yes",
  "Height Adjustable Front Seat Belts": "Yes",
  "Rear AC Vents": "Yes",
  "Cruise Control": "Yes",
  "Parking Sensors": "Rear",
  "Foldable Rear Seat": "60:40 Split",
  "KeyLess Entry": "Yes",
  "Engine Start/Stop Button": "Yes",
  "Cooled Glovebox": "Yes",
  "Voice Commands": "Not Available",
  "Paddle Shifters": "Not Available",
  "USB Charger": "Front & Rear",
  "Central Console Armrest": "With Storage",
  "Tailgate Ajar Warning": "Yes",
  "Luggage Hook & Net": "Yes",
  "Idle Start-Stop System": "Yes",
  "Rear Window Sunblind": "Yes",
  "Follow Me Home Headlamps": "Yes",
  "Additional Features": "Sunglass Holder",
  "Voice assisted sunroof": "No",
  "Power Windows": "Front & Rear",
  "Cup Holders": "Front Only",
  "Tachometer": "Yes",
  "Leather Wrapped Steering Wheel": "Yes",
  "Leather wrap gear-shift selector": "Yes",
  "Glove Box": "Yes",
  "Digital Cluster": "Yes",
  "Digital Cluster Size": { "value": 4.5, "unit": "Inch" },
  "Upholstery": "Fabric",
  "Adjustable Headlamps": "Yes",
  "Rain Sensing Wiper": "Not Available",
  "Rear Window Wiper": "Yes",
  "Rear Window Washer": "Yes",
  "Rear Window Defogger": "Yes",
  "Alloy Wheels": "Yes",
  "Rear Spoiler": "Yes",
  "Outside Rear View Mirror Turn Indicators": "Yes",
  "Roof Rails": "Yes",
  "Automatic Headlamps": "Yes",
  "Antenna": "Micro",
  "Sunroof": "Not Available",
  "Boot Opening": "Electronic",
  "Puddle Lamps": "Not Available",
  "Outside Rear View Mirror (ORVM)": "Powered & Folding",
  "Tyre Size": "215/60 R17",
  "Tyre Type": "Radial Tubeless",
  "LED DRLs": "Yes",
  "LED Headlamps": "Yes",
  "LED Taillights": "Yes",
  "Anti-lock Braking System (ABS)": "Yes",
  "Central Locking": "Yes",
  "Child Safety Locks": "Yes",
  "Anti-Theft Alarm": "Yes",
  "No. of Airbags": "6",
  "Driver Airbag": "Yes",
  "Passenger Airbag": "Yes",
  "Side Airbag": "Yes",
  "Side Airbag-Rear": "Not Available",
  "Day & Night Rear View Mirror": "Yes",
  "Curtain Airbag": "Yes",
  "Electronic Brakeforce Distribution (EBD)": "Yes",
  "Seat Belt Warning": "Yes",
  "Door Ajar Warning": "Yes",
  "Traction Control": "Not Available",
  "Tyre Pressure Monitoring System (TPMS)": "Yes",
  "Engine Immobilizer": "Yes",
  "Electronic Stability Control (ESC)": "Yes",
  "Rear Camera": "With Guidedlines",
  "Anti-Theft Device": "Yes",
  "Anti-Pinch Power Windows": "Driver's Window",
  "Speed Alert": "Yes",
  "Speed Sensing Auto Door Lock": "Yes",
  "ISOFIX Child Seat Mounts": "Yes",
  "Pretensioners & Force Limiter Seatbelts": "Driver and Passenger",
  "Hill Descent Control": "Not Available",
  "Hill Assist": "Yes",
  "Impact Sensing Auto Door Unlock": "Yes",
  "360 View Camera": "Not Available",
  "Radio": "Not Available",
  "Wireless Phone Charging": "Not Available",
  "Bluetooth Connectivity": "Not Available",
  "Touchscreen": "Not Available",
  "Touchscreen Size": "inch",
  "Android Auto": "Not Available",
  "Apple CarPlay": "Not Available",
  "Usb Ports": "Yes",
  "Inbuilt Apps": "No",
  "Speakers": "Not Available",
  "Forward Collision Warning": "Not Available",
  "Blind Spot Collision Avoidance Assist": "Not Available",
  "Lane Departure Warning": "Not Available",
  "Lane Keep Assist": "Not Available",
  "Driver Attention Warning": "Not Available",
  "Adaptive Cruise Control": "Not Available",
  "Adaptive High Beam Assist": "Not Available",
  "Rear Cross Traffic Alert": "Not Available",
  "Rear Cross Traffic Collision-Avoidance Assist": "Not Available",
  "Blind Spot Monitor": "Not Available",
  "Remote Immobiliser": "Yes",
  "Remote Vehicle Status Check": "Yes",
  "Digital Car Key": "Not Available",
  "Over the Air (OTA) Updates": "Not Available",
  "Google / Alexa Connectivity": "Not Available",
  "Remote Door Lock/Unlock": "Yes",
  "Remote Vehicle Ignition Start/Stop": "Yes",
  "Engine Displacement": { "value": "1493", "unit": "cc" },
  "Body Type": "SUV"
};
