export const theme = {
  layout: {
    pageContainer: "flex-1 p-12 min-h-screen bg-slate-50/50",
    contentWrapper: "w-full space-y-8",
    headerWrapper: "flex flex-col md:flex-row md:items-center justify-between border-b border-slate-200 pb-8 gap-6",
    grid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 pb-20",
    listWrapper: "w-full min-h-[60vh] space-y-4",
    tableHeader: "grid grid-cols-12 gap-4 px-6 py-3 text-[10px] font-bold text-slate-500 uppercase tracking-widest border-b border-slate-200",
    listContent: "space-y-3",
    section: "space-y-4",
    sectionHeader: "text-xs font-bold text-slate-900 uppercase tracking-wider flex items-center gap-3",
    sectionDivider: "w-8 h-[1px] bg-slate-300",
    grid2: "grid grid-cols-1 md:grid-cols-2 gap-6",
    grid3: "grid grid-cols-1 md:grid-cols-3 gap-6",
    grid4: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6",
    flexBetween: "flex items-center justify-between",
    flexRowGap: "flex items-center gap-3",
  },
  typography: {
    h1: "text-3xl font-black text-slate-900 tracking-tight",
    h1Highlight: "text-slate-400 text-xl ml-2 font-bold tracking-widest uppercase",
    subtitle: "text-[10px] font-bold text-slate-500 uppercase tracking-[0.2em]",
    detailTitle: "text-4xl md:text-5xl font-black text-slate-900 tracking-tighter leading-none",
    cardTitle: "text-2xl font-black text-slate-900 group-hover:text-blue-600 transition-colors line-clamp-1",
    cardSubtitle: "text-xs text-slate-500 mt-2 font-medium line-clamp-2",
    pageTitle: "text-2xl font-bold text-slate-900 tracking-tight",
    sectionTitle: "text-xs font-bold text-slate-900 uppercase tracking-wider",
    cardHeading: "text-base font-bold text-slate-900",
    body: "text-xs text-slate-600 font-normal leading-relaxed",
    bodyMuted: "text-xs text-slate-500 font-normal",
    label: "block text-xs font-semibold text-slate-700 mb-1.5",
    caption: "text-[11px] font-semibold text-slate-400 uppercase tracking-wider",
    statNumber: "text-2xl font-bold text-slate-900 tracking-tight",
    statLabel: "text-xs font-normal text-slate-500 mt-0.5",
    badgeText: "text-[11px] font-semibold uppercase tracking-wider",
  },
  buttons: {
    primary: "px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold transition-all flex items-center gap-2 justify-center shrink-0 disabled:opacity-50 disabled:cursor-not-allowed",
    secondary: "px-4 py-2 rounded-xl bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-semibold transition-all flex items-center gap-2 justify-center shrink-0 disabled:opacity-50 disabled:cursor-not-allowed",
    ghost: "px-3 py-1.5 rounded-xl text-xs font-semibold text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition-colors flex items-center gap-2",
    danger: "px-4 py-2 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-semibold transition-all flex items-center gap-2 justify-center shrink-0",
    outline: "px-3.5 py-2 rounded-xl border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs font-semibold transition-all flex items-center gap-2",
    icon: "p-2.5 rounded-xl border border-slate-200 bg-white text-slate-600 hover:text-slate-900 hover:bg-slate-50 transition-all shrink-0 flex items-center justify-center",
    tabContainer: "flex items-center gap-2",
    tab: "flex items-center gap-2.5 px-4 py-2.5 rounded-3xl text-[11px] font-semibold uppercase tracking-wider transition-all duration-200 group relative shrink-0",
    tabActive: "bg-slate-50 text-slate-900 border border-slate-200 font-bold",
    tabInactive: "text-slate-500 bg-transparent border border-transparent hover:bg-slate-50 hover:border-slate-200 hover:text-slate-900",
    topbarTabContainer: "flex items-center gap-2",
    topbarTab: "flex items-center gap-2.5 px-4 py-2.5 rounded-3xl text-[11px] font-semibold uppercase tracking-wider transition-all duration-200 group relative shrink-0",
    topbarTabActive: "bg-slate-50 text-slate-900 border border-slate-200 font-bold",
    topbarTabInactive: "text-slate-500 bg-transparent border border-transparent hover:bg-slate-50 hover:border-slate-200 hover:text-slate-900",
  },
  forms: {
    input: "w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-medium text-slate-900 outline-none focus:border-slate-900 focus:bg-white transition-all placeholder:text-slate-400",
    select: "w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-medium text-slate-900 outline-none focus:border-slate-900 focus:bg-white transition-all",
    textarea: "w-full bg-slate-50 border border-slate-200 rounded-xl p-4 text-xs font-medium text-slate-900 outline-none focus:border-slate-900 focus:bg-white transition-all placeholder:text-slate-400 resize-none",
    label: "block text-xs font-semibold text-slate-700 mb-1.5",
    help: "text-[11px] text-slate-400 font-normal mt-1",
    error: "text-[11px] text-rose-500 font-medium mt-1",
    prefixWrapper: "relative flex items-center",
    prefixIcon: "absolute left-3.5 text-slate-400 pointer-events-none",
    inputWithPrefix: "w-full bg-slate-50 border border-slate-200 rounded-xl pl-10 pr-4 py-2.5 text-xs font-medium text-slate-900 outline-none focus:border-slate-900 focus:bg-white transition-all placeholder:text-slate-400",
    segmentedContainer: "flex items-center bg-slate-100 p-1 rounded-xl border border-slate-200",
    segmentedItemActive: "flex-1 py-1.5 rounded-lg text-xs font-semibold bg-white text-slate-900 transition-all",
    segmentedItemInactive: "flex-1 py-1.5 rounded-lg text-xs font-semibold text-slate-500 hover:text-slate-900 transition-all",
  },
  badges: {
    neutral: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-slate-100 text-slate-700 border border-slate-200",
    success: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-emerald-50 text-emerald-700 border border-emerald-200",
    warning: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-amber-50 text-amber-700 border border-amber-200",
    danger: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-rose-50 text-rose-700 border border-rose-200",
    info: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-blue-50 text-blue-700 border border-blue-200",
    indigo: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-indigo-50 text-indigo-700 border border-indigo-200",
    purple: "px-2.5 py-0.5 rounded-md text-[11px] font-semibold uppercase tracking-wider bg-purple-50 text-purple-700 border border-purple-200",
  },
  cards: {
    panel: "bg-white p-8 rounded-3xl border border-slate-200 space-y-6",
    panelHeader: "flex items-center justify-between pb-4 border-b border-slate-100",
    statCard: "bg-white p-6 rounded-2xl border border-slate-200 space-y-3 transition-all",
    statIcon: "w-10 h-10 rounded-xl flex items-center justify-center font-bold text-xs shrink-0",
    interactive: "bg-white p-6 rounded-2xl border border-slate-200 hover:border-slate-300 transition-all flex flex-col justify-between group cursor-pointer",
    emptyState: "p-12 rounded-2xl border border-dashed border-slate-300 bg-slate-50/30 flex flex-col items-center justify-center text-center space-y-4",
  },
  tables: {
    container: "bg-white rounded-3xl border border-slate-200 overflow-hidden",
    table: "w-full text-left text-xs border-collapse",
    thead: "bg-slate-50 border-b border-slate-200 text-slate-500 text-[11px] font-semibold uppercase tracking-wider",
    th: "px-6 py-3.5 font-semibold text-slate-500 text-[11px] uppercase tracking-wider",
    tbody: "divide-y divide-slate-100 text-slate-700",
    tr: "hover:bg-slate-50/80 transition-colors group",
    td: "px-6 py-4 align-middle",
    pagination: "px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500",
    paginationBtn: "p-2 rounded-xl border border-slate-200 bg-white text-slate-600 hover:bg-slate-100 hover:text-slate-900 disabled:opacity-30 disabled:cursor-not-allowed transition-all",
  },
  modals: {
    backdrop: "fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200",
    dialog: "bg-white rounded-3xl border border-slate-200 max-w-lg w-full p-8 space-y-6 relative animate-in zoom-in-95 duration-200",
    header: "flex items-start justify-between gap-4",
    title: "text-base font-bold text-slate-900",
    description: "text-xs text-slate-500 font-normal mt-1 leading-relaxed",
    body: "space-y-4 text-xs text-slate-600 leading-relaxed",
    footer: "flex items-center justify-end gap-3 pt-6 border-t border-slate-100",
    drawer: "fixed top-0 right-0 bottom-0 z-50 w-full max-w-md bg-white border-l border-slate-200 p-8 flex flex-col justify-between animate-in slide-in-from-right duration-300",
  },
  alerts: {
    success: "p-4 bg-emerald-50 border border-emerald-200 rounded-2xl flex items-center gap-3 text-emerald-800 text-xs font-medium",
    danger: "p-4 bg-rose-50 border border-rose-200 rounded-2xl flex items-center gap-3 text-rose-700 text-xs font-medium",
    warning: "p-4 bg-amber-50 border border-amber-200 rounded-2xl flex items-center gap-3 text-amber-800 text-xs font-medium",
    info: "p-4 bg-blue-50 border border-blue-200 rounded-2xl flex items-center gap-3 text-blue-800 text-xs font-medium",
  },
  pipeline: {
    board: "grid grid-cols-1 md:grid-cols-4 gap-6 items-start",
    column: "bg-slate-100/60 p-4 rounded-3xl border border-slate-200/80 space-y-4 min-h-[500px] flex flex-col",
    columnHeader: "flex items-center justify-between px-2 pb-2 border-b border-slate-200",
    card: "bg-white p-4 rounded-2xl border border-slate-200 hover:border-slate-300 transition-all space-y-3 cursor-pointer group",
  },
  ui: {
    accordionContainer: "border border-slate-200 rounded-2xl divide-y divide-slate-200 overflow-hidden",
    accordionBtn: "w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-50 transition-colors text-xs font-bold text-slate-900",
    accordionContent: "px-6 pb-4 pt-1 text-xs text-slate-600 leading-relaxed bg-slate-50/50",
    slider: "w-full accent-slate-900 cursor-pointer",
    progressBarTrack: "w-full h-2.5 bg-slate-200 rounded-full overflow-hidden",
    progressBarFill: "h-full bg-slate-900 rounded-full transition-all",
    dropzone: "border-2 border-dashed border-slate-300 rounded-2xl p-8 flex flex-col items-center justify-center text-center hover:border-slate-400 transition-colors cursor-pointer bg-slate-50/30",
    toast: "fixed bottom-6 right-6 z-50 p-4 bg-slate-900 text-white rounded-2xl flex items-center gap-3 text-xs font-medium border border-slate-800 animate-in slide-in-from-bottom-5",
    skeletonPulse: "animate-pulse bg-slate-200 rounded",
  },
  // Backwards-compatible components dictionary:
  components: {
    searchInput: "bg-white border border-slate-200 rounded-2xl py-3 pl-10 pr-6 text-xs text-slate-900 focus:ring-1 focus:ring-slate-300 transition-all w-full md:w-64 hover:bg-slate-50 placeholder-slate-400 outline-none",
    iconButton: "p-3 bg-white border border-slate-200 rounded-2xl text-slate-500 hover:text-slate-900 hover:bg-slate-50 transition-all shrink-0",
    card: "group cursor-pointer relative bg-white border border-slate-200 p-7 rounded-[2rem] transition-all hover:border-blue-200 overflow-hidden",
    cardDecorativeBg: "absolute top-0 right-0 -translate-y-1/4 translate-x-1/4 w-32 h-32 bg-slate-50 rounded-full blur-3xl group-hover:bg-blue-50 transition-all",
    cardIconContainer: "w-14 h-14 rounded-2xl bg-slate-50 flex items-center justify-center text-slate-900 font-black text-xl border border-slate-200 group-hover:border-blue-200 transition-all",
    cardBadge: "px-3 py-1 bg-slate-50 border border-slate-200 rounded-full text-[8px] font-black uppercase tracking-tighter text-slate-500",
    cardFooter: "pt-4 border-t border-slate-100 flex items-center justify-between",
    cardFooterItem: "flex items-center gap-2 text-slate-500",
    cardFooterText: "text-[10px] font-bold uppercase tracking-widest",
    listItem: "group grid grid-cols-12 gap-4 items-center p-5 rounded-2xl border bg-white border-slate-200 hover:bg-slate-50 hover:border-blue-200 transition-all",
    paginationWrapper: "flex items-center justify-between pt-4 border-t border-slate-200",
    backButton: "group flex items-center gap-3 px-5 py-2.5 bg-white border border-slate-200 rounded-2xl text-slate-500 hover:text-slate-900 hover:bg-slate-50 transition-all",
    detailHero: "relative bg-white border border-slate-200 rounded-[3rem] p-12 overflow-hidden",
    detailHeroBadge: "w-24 h-24 rounded-3xl bg-slate-50 border border-slate-200 flex items-center justify-center text-slate-900 text-3xl font-black uppercase",
    sectionWrapper: "bg-white border border-slate-200 rounded-[3rem] p-10",
    badgeLabel: "flex items-center gap-2 px-3 py-1 bg-slate-50 rounded-full border border-slate-200",
    // Expanded component helpers:
    buttonPrimary: "px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold transition-all flex items-center gap-2 justify-center shrink-0 disabled:opacity-50 disabled:cursor-not-allowed",
    buttonSecondary: "px-4 py-2 rounded-xl bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-semibold transition-all flex items-center gap-2 justify-center shrink-0 disabled:opacity-50 disabled:cursor-not-allowed",
    panel: "bg-white p-8 rounded-3xl border border-slate-200 space-y-6",
  }
};

export type Theme = typeof theme;
